[env:elecrow-crowpanel-128]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_extra_dirs =
    Arduino/libraries

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4

; Match the N16R8 (16MB flash, 8MB OPI PSRAM)
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = partitions.csv
board_build.filesystem = spiffs

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -I"${PROJECT_DIR}/src"
    -I"${PROJECT_DIR}/Arduino/libraries"
    -DLV_CONF_INCLUDE_SIMPLE
